### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/michaeldyrynda/laravel-efficient-uuid/pull/62/commits/95addd676ff6a2617d5954c89cb42d97ab3fb3ca?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-efficient-uuid.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "dyrynda/laravel-efficient-uuid": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by masterix21** [comment]
It can't work with `"dyrynda/laravel-model-uuid": "^7.0"`.

**Comment by masterix21** [comment]
@michaeldyrynda: do you have any plans to upgrade to Laravel 11? Thanks for your effort.

**Comment by padre** [comment]
@michaeldyrynda, could you update please?

Thanks!

**Comment by michaeldyrynda** [comment]
I’m deprecating this package in favour of combining the functionality into [laravel-model-uuid](https://github.com/michaeldyrynda/laravel-model-uuid/releases/tag/8.0.0-beta.1)

Are you folks able to test that beta release? It should be suitable, but wanted to get some eyeballs across it first. 

Work has been busy and I haven’t had a chance to spend much time on it since tagging the release.

**Comment by padre** [comment]
@michaeldyrynda  Next week I'll try to test it out and get back to you with anything.

Thank you very much for your work.

**Comment by michaeldyrynda** [comment]
If you need Laravel 11 support, please swap to [dyrynda/laravel-model-uuid](https://github.com/michaeldyrynda/laravel-model-uuid).

**Pull request closed without merging**
